services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: etulas
      POSTGRES_USER: etulas
      POSTGRES_PASSWORD: etulas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: etulas
      RABBITMQ_DEFAULT_PASS: etulas
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  rabbitmq_data: